### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by freedom2012** [Semantic-Org/Semantic-UI-Angular#62]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle semantic-ui-angular@0.0.0~prebuild: semantic-ui-angular@0.0.0
6 silly lifecycle semantic-ui-angular@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle semantic-ui-angular@0.0.0~build: semantic-ui-angular@0.0.0
8 verbose lifecycle semantic-ui-angular@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle semantic-ui-angular@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Hejc\Semantic-UI-Angular-master\node_modules.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Git\bin;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.2\bin\;C:\Users\Linzc\AppData\Roaming\npm;D:\Program Files (x86)\SSH Communications Security\SSH Secure Shell
10 verbose lifecycle semantic-ui-angular@0.0.0~build: CWD: D:\Hejc\Semantic-UI-Angular-master
11 silly lifecycle semantic-ui-angular@0.0.0~build: Args: [ '/d /s /c', 'rm -rf dist && node_modules/.bin/webpack' ]
12 silly lifecycle semantic-ui-angular@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle semantic-ui-angular@0.0.0~build: Failed to exec build script
14 verbose stack Error: semantic-ui-angular@0.0.0 build: `rm -rf dist && node_modules/.bin/webpack`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid semantic-ui-angular@0.0.0
16 verbose cwd D:\Hejc\Semantic-UI-Angular-master
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
19 error node v6.1.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error semantic-ui-angular@0.0.0 build: `rm -rf dist && node_modules/.bin/webpack`
22 error Exit status 1
23 error Failed at the semantic-ui-angular@0.0.0 build script 'rm -rf dist && node_modules/.bin/webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the semantic-ui-angular package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rm -rf dist && node_modules/.bin/webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs semantic-ui-angular
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls semantic-ui-angular
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

What is the problem?

**Comment by ppatrik** [comment]
Just change line in package.json from this
`"build": "rm -rf dist && node_modules/.bin/webpack"`
to this
`"build": "node_modules/.bin/webpack"`

Then you need manualy remove dist folder before running build
